services:
  postgres:
    container_name: db
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    command: >
      postgres -c listen_addresses='*'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - groups
    restart: unless-stopped

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    volumes:  
      - ./backend:/app
    working_dir: /app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    networks:
      - groups
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  groups:
    driver: bridge


volumes:
  postgres:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './postgres'
  backend:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend'